sudo: required
dist: trusty
language: python
python:
  - "3.6"
env:
  - BOTO_CONFIG=/tmp/nowhere
install:
  # install miniconda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # build test environment
  - conda env create -f ./environment.yml
  - source activate py-object-factory
script:
  - pytest -v --cov --cov-report term:skip-covered
after_success:
  - codecov
